on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'OpenSilver Version'     
        required: true
        default: 'latest'
jobs:
  printInputs:
    runs-on: windows-latest
    steps:
    - run: |
        $version = "${{ github.event.inputs.branch }}"
        if ($version -eq "latest") {
          $version = nuget list -Source https://www.myget.org/F/opensilver/api/v3/index.json -Prerelease | ? { $_ -match "^OpenSilver\s+(.*)" } | ForEach { $_.split(" ")[1] }
        }
        echo "Version: $version"
        echo ::set-env name=OPENSILVER_VERSION::$version
    - run: |
        echo "Branch: ${{ env.OPENSILVER_VERSION }}"
