name: Try Packages
on:
  push:
    branches:
      - main
jobs:
  OpenSilver-Build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Experiment
        run: |
          dotnet new console --name OctocatApp
          dotnet pack OctocatApp\OctocatApp.csproj --configuration Release /p:RepositoryUrl=https://github.com/jacob-l/try-nuget-packages
          dotnet nuget push "OctocatApp\bin\Release\OctocatApp.1.0.0.nupkg" --source https://nuget.pkg.github.com/jacob-l/index.json
